/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group2.panel;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author RapRap
 */
public class qrReader extends javax.swing.JPanel {

	/**
	 * Creates new form qrReader
	 */
	public qrReader() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                CardButton = new javax.swing.JLabel();
                BookButton = new javax.swing.JLabel();
                jTextField2 = new javax.swing.JTextField();
                SaveButton = new javax.swing.JLabel();
                CancelButton = new javax.swing.JLabel();

                setBackground(new java.awt.Color(0,0,0,1));
                setForeground(new java.awt.Color(0,0,0,1));

                jPanel2.setMaximumSize(new java.awt.Dimension(294, 150));
                jPanel2.setMinimumSize(new java.awt.Dimension(294, 150));
                jPanel2.setPreferredSize(new java.awt.Dimension(294, 150));

                CardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icon/card.png"))); // NOI18N
                CardButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                CardButtonMouseClicked(evt);
                        }
                });

                BookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icon/open-book.png"))); // NOI18N
                BookButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                BookButtonMouseClicked(evt);
                        }
                });

                jTextField2.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
                jTextField2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField2ActionPerformed(evt);
                        }
                });

                SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icon/save (1).png"))); // NOI18N
                SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                SaveButtonMouseClicked(evt);
                        }
                });

                CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/group2/icon/cancel (1).png"))); // NOI18N
                CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                CancelButtonMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(CardButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(CancelButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(BookButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(SaveButton)))
                                .addGap(10, 10, 10))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(560, 560, 560)
                                                .addComponent(CardButton)
                                                .addGap(16, 16, 16)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(170, 170, 170)
                                                .addComponent(CancelButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(560, 560, 560)
                                                .addComponent(BookButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(860, 860, 860)
                                                .addComponent(SaveButton)))
                                .addGap(156, 156, 156))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void CardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardButtonMouseClicked
                // TODO add your handling code here:
        }//GEN-LAST:event_CardButtonMouseClicked

        private void BookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookButtonMouseClicked
                // TODO add your handling code here:
        }//GEN-LAST:event_BookButtonMouseClicked

        private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextField2ActionPerformed

        private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
                // TODO add your handling code here:
        }//GEN-LAST:event_SaveButtonMouseClicked

        private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
                // TODO add your handling code here:
        }//GEN-LAST:event_CancelButtonMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel BookButton;
        private javax.swing.JLabel CancelButton;
        private javax.swing.JLabel CardButton;
        private javax.swing.JLabel SaveButton;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTextField jTextField2;
        // End of variables declaration//GEN-END:variables
}
